#!/bin/bash
#
#    50-check-updates - Poll for available updates
#    Copyright (C) 2017 Malin von Matern
#
#    Authors: Malin von Matern
#

# Update source, but only if it hasn't been done today
#var_dir=/usr/lib/update-notifier/update-motd-last-update
#if [ -f $var_dir ]; then
#    source $var_dir
#    if [ $last_update -lt $(date +%Y%m%d) ]; then
#        apt-get update -qq -d
#        echo "last_update="$(date +%Y%m%d) > $var_dir
#    fi
#fi
# Hopefully moved to cron.daily (apt)
